### ISSUE TITLE
[NavigationCodelab] UnknownPluginException: Plugin [id: 'com.diffplug.spotless', version: '6.21.0'] was not found

### ISSUE THREAD

**Issue by Alienstemple** [android/codelab-android-compose#384]
Getting the following error while trying to open NavigationCodelab in Android Studio:
```
* Exception is:
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'com.diffplug.spotless', version: '6.21.0'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.21.0')
  Searched in the following repositories:
Gradle Central Plugin Repository
at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:125)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:42)
```

**Comment by Goooler** [comment]
This could be closed now, it's outdated. Spotless has been updated to `6.25.0`.
